server:
  port: 8089
  gu:
    security:
    # 配置oauth2
      oauth2:
        storeType: jwt
spring:
  redis:
    password: sylincom
    host: 39.104.146.109
    port: 6379
    # 连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8
  gu:
    security:
      oauth2:
        store-type: jwt

