server:
  port: 9090
spring:
  application:
    name: gateway-business
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: test
          uri: http://www.baidu.com
          predicates:
            - Path=/api/test
          filters:
          #  - StripPrefix=1
          # - PreserveHostHeader
         - id: uua-business
           uri: lb://uua-business
           predicates:
             - Path=/api/oauth/*
    nacos:
      discovery:
        server-addr: 10.1.2.4:8848