server:
  port: 8089
spring:
  application:
    name: uua-business
  redis:
    password: sylincom
    host: 39.104.146.109
    port: 6379
    # 连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8
  gu:
    security:
      oauth2:
        store-type: redis
        clients:
          - client: gu
            secret: gu
      validate-code:
        login-code:
          expiration: 240000

  cloud:
    nacos:
      discovery:
        server-addr: 10.1.2.4:8848


logging:
  level:
    com:
      gu: debug
