server:
  port: 8089
spring:
  application:
    name: uua-business
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true


  redis:
    password: sylincom
    host: 39.104.146.109
    port: 6379
    # 连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8
  gu:
    security:
      oauth2:
        store-type: redis
        clients:
          - client: gu
            secret: gu
      validate-code:
        login-code:
          expiration: 240000

  cloud:
    nacos:
      discovery:
        server-addr: 10.1.2.4:8848


logging:
  level:
    com:
      gu: debug
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: true
    max-connections: 1000
    max-connections-per-route: 100
  compression:
    request:
      mime-types: ext/xml,application/xml,application/json
      min-request-size: 2048
      enabled: true
    response:
      enabled: true


